### ISSUE TITLE
i get upset while trying to install it

### ISSUE THREAD

**Issue by ahmeteid7** [adammpkins/llama-terminal-completion#10]
it's difficult to install it, the instructions is not clear, i wish if it is clear, also i don't know it will require a big data while download from internet or what, i get long way that consume a lot of bandwidth from internet when run ./configure_llama_linux.sh.

please make it easy to install, and show the requirements of area that will consume while installing and the consume bandwidth

**Comment by adammpkins** [comment]
Hi there,

Thank you for reaching out. We appreciate your feedback on the installation process.

1. **Installation Clarity**: We aim to keep the installation as straightforward as possible with the `configure_llama_linux.sh` script. This script is designed to handle everything from dependencies to environment configuration. If there's a specific step that's causing confusion, could you let us know? We're here to clarify.

2. **Bandwidth and Data Usage**: Given that this is a local installation of a large language model (LLM), the nature of the software inherently requires a substantial download. Large language models, by their very definition, are massive datasets that power the AI's capabilities. As such, expecting a significant download is part and parcel of setting up a local LLM. We don't provide specific download sizes simply because they can vary significantly with each update and model version, but it's safe to assume that it will be several gigabytes. If bandwidth is a concern, this installation might be better suited to an environment with a more robust internet connection.

3. **Installation Requirements**:
    - **Disk Space**: Make sure there's ample space on your machine—how much will depend on the model version, but expect to need several gigabytes.
    - **Internet Connection**: A solid and fast internet connection is not just recommended; it's necessary. This isn't the kind of download you'd want to run on a metered or slow connection.

**Installing the Assistant**:
- Ensure you're in the directory with `configure_llama_linux.sh`.
- Run `./configure_llama_linux.sh` in your terminal and follow the prompts.
- Sit back; this might take a while, given the large size of the files being downloaded.

We understand that this might not be the feedback you were hoping for, but the reality of downloading and setting up a local instance of a large language model is that it comes with certain prerequisites and expectations, bandwidth being one of them. We're continuously working to optimize how we deliver our software, but the size of the model and the initial setup requirements are currently fixed elements of the process.

**Comment by ahmeteid7** [comment]
> @ahmeteid7 Hi there,
> 
> Thank you for reaching out. We appreciate your feedback on the installation process.
> 
> 1. **Installation Clarity**: We aim to keep the installation as straightforward as possible with the `configure_llama_linux.sh` script. This script is designed to handle everything from dependencies to environment configuration. If there's a specific step that's causing confusion, could you let us know? We're here to clarify.
> 2. **Bandwidth and Data Usage**: Given that this is a local installation of a large language model (LLM), the nature of the software inherently requires a substantial download. Large language models, by their very definition, are massive datasets that power the AI's capabilities. As such, expecting a significant download is part and parcel of setting up a local LLM. We don't provide specific download sizes simply because they can vary significantly with each update and model version, but it's safe to assume that it will be several gigabytes. If bandwidth is a concern, this installation might be better suited to an environment with a more robust internet connection.
> 3. **Installation Requirements**:
>    
>    * **Disk Space**: Make sure there's ample space on your machine—how much will depend on the model version, but expect to need several gigabytes.
>    * **Internet Connection**: A solid and fast internet connection is not just recommended; it's necessary. This isn't the kind of download you'd want to run on a metered or slow connection.
> 
> **Installing the Assistant**:
> 
> * Ensure you're in the directory with `configure_llama_linux.sh`.
> * Run `./configure_llama_linux.sh` in your terminal and follow the prompts.
> * Sit back; this might take a while, given the large size of the files being downloaded.
> 
> We understand that this might not be the feedback you were hoping for, but the reality of downloading and setting up a local instance of a large language model is that it comes with certain prerequisites and expectations, bandwidth being one of them. The size of the model and the initial setup requirements are currently fixed elements of the process.
instead of install it locally, can i reach to that api via internet ?
